### ISSUE TITLE
Add meta descriptions

### ISSUE THREAD

**Issue by samajammin** [ethereum/cryptography-research-website#24]
Noticed the recent blog post doesn't display a meta description:

<img width="468" alt="Screen Shot 2022-06-07 at 2 23 37 PM" src="https://user-images.githubusercontent.com/8097623/172485212-e62a2563-ef7a-4a49-ab0a-aa8806158012.png">

Let's add those - I see TODOs 😄 
- [x] https://github.com/ethereum/cryptography-research-website/blob/master/src/pages/blog/index.tsx#L95
- [x] https://github.com/ethereum/cryptography-research-website/blob/master/src/pages/blog/%5Bslug%5D.tsx#L72
- [x] Update README to include post descriptions

**Comment by samajammin** [comment]
On a related note, I'm noticing that the title tags for blog posts are likely going to be too long, e.g. 
https://crypto.ethereum.org/blog/groth-sahai-blogpost
```
Groth-Sahai Proofs Are Not That Scary | Ethereum Foundation Cryptography Research
```

Can we customize the string we append? i.e. 
```
{post-title} | EF Cryptography Research
```
